[project]
name = "jaxonlayers"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.21.0",
    "equinox>=0.13.0",
    "jax>=0.8.0",
    "jaxtyping>=0.3.2",
]

[tool.setuptools]
packages = ["jaxonlayers"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "statedict2pytree>=1.0.1",
    "torchvision>=0.23.0",
    "torch>=2.8.0",
    "pre-commit>=4.3.0",
    "matplotlib>=3.10.7",
]

[tool.ruff]
ignore = ["F722", "F821"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
